# Dicts for Roadside Encounters
# Each type of encounter will have its own dictionary, with combat encounters having CR able to be output

# Sources:
# https://nerdsonearth.com/2016/02/100-dungeons-and-dragons-roadside-encounters-2/
# https://litrpgreads.com/blog/rpg/random-encounter-table-non-combat-d20
# https://litrpgreads.com/blog/rpg/100-dnd-random-road-encounters
# 100 Roadside Encounter Ideas by Johnn Four (johnn@roleplayingtips.com)

# Dict for handling rp/sidequest based events. Currently there are combat events in here as there is no combat event dict yet.

event = {
    # From nerdsonearth:
    1: "A huge nest has fallen from a tree on the side of the road. The strange-looking eggs within seem on the verge of hatching.",
    2: "A dwarf falls from the sky onto the road with a splat. (Did a creature drop it, was he launched into the air, did he fall from a floating fortress?)",
    3: "A row of severed heads on spikes and a warning sign claiming, 'Dis Rode Belong Negan'",
    4: "A very small goblin wearing an old carpet as a cape leaps into the path and demands tribute.",
    5: "A crazed halfling, starved out of his mind, jumps to the backs of the PCs and rips their packs apart with his teeth in search of food.",
    6: "A bounty hunter tracks his target.",
    7: "A lush garden is filled with ripe vegetables. It is protected by a magical ward, but what is triggered when entering the garden?",
    8: "A monstrous mount is ridden by a gnome. Friend or foe?",
    9: "Two guards hold a wanted poster. They carefully studies the party as they pass by.",
    10: "A smiling roadside merchant roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
    11: "A chatty bard walks alongside the party. Time for an exposition dump!",
    12: "A bridle ties a well-groomed speckled horse to a nearby tree. The horse is fitted with an elegant but empty saddle. Who does it belong to? Do the PCs take it?",
    13: "A powerful storm forced you to take the only available refuge: an elderly couple's home just off the side of the road. The two room home holds numerous open cups of the same pungent liquid.",
    14: "A naked bard asks for a lift to the nearest inn where he left his clothes and money.",
    15: "Alongside the road, a charlatan asks the party if they want to see a performance of his trained pets. The slightest affirmative answer causes Steve to give a whistle, and a huge swarm of ravenous locusts suddenly manifests.",
    16: "A fat friar hurries past the PCs mumbling, 'It isn't fair...'",
    17: "A witch is tied to a stake, the body still smoking",
    18: "Three young men work on tipping over an occupied outhouse.",
    19: "The PCs feel like they are being followed. Who is hunting them?",
    20: "Three types of meat hang on a spit over a campfire. It is clear that it is three types of humanoids that hang over the flames.",
    21: "A well-spoken bugbear wearing fine studded leather armor is trapped under a fallen tree. He begs the party to come to his aid.",
    22: "A ranger stops by the group's camp one night and gives them advice on the trail ahead, including places to camp and a tavern where they can get good rates if they mention his name. All his advice is impeccable, but when they mention his name at the tavern, they're told he died years ago on that very road.",
    23: "A shopping list for potions lies on the ground.",
    24: "You find the remains of a pouch that contains coins from a land you do not recognize.",
    25: "The party hears a long stream of curses further up the road. Then they spot a head in the road. A person is still alive, buried up to his neck!",
    26: "An arrow hits a nearby trunk, a message wrapped around the shaft.",
    27: "A loaded wagon travels down the road toward the party, but it has no apparent means of propulsion.",
    28: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    29: "As bandits attack, the PCs realize a friend of theirs is among the robbers.",
    30: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    31: "A tree falls onto the road. Then a fireball blows up the tree. It appears the PCs are in the middle of a skirmish between a witch and wizards.",
    32: "Flowers by the roadside turn their heads to follow the party, and they're getting larger.",
    33: "An overturned beer cart lies in the road. Nearby, an enormous troll snores loudly, surrounded by empty kegs.",
    34: "A set of shackles lies at the side of the road.",
    35: "A village can be seen to the west. It isn't on any of the maps.",
    36: "Three pilgrims trudge along the dusty road, an old man and two young men. Simple travelers? Or are they more than they seem?",
    37: "You stumble upon an old scroll case wedged between a tangle of tree branches. Inside is a village's charter of rights and freedoms.",
    38: "A dead magic user clutches a scroll in his stiff hand. The scroll says something important.",
    39: "A single giant footprint lies along the path. There are no other signs of such footprints in the area.",
    40: "An exotic, almost alien weapon or tool lies on the side of the road.",
    41: "Two other adventuring groups are arguing in the middle of the road.",
    42: "You see a man-sized shadow from the left side of the road waving its arms at you. 'Over here, quickly, I've caught one!'",
    43: "A person fleeing arranged marriage seeks refuge with the PCs.",
    44: "Picked mushrooms lay on stump to dry.",
    45: "A strange old man offers the PCs a scroll in a language they cannot read.",
    46: "Gnomes are holding a yard sale! They have any number of strange and fascinating contraptions.",
    47: "Someone has scattered caltrops across the road.",
    48: "You encounter a monk, a monkey, a turtle and a pig, all heading west.",
    49: "A weathered sign points off the road, yet with no apparent trail to follow.",
    50: "A formerly brilliant wizard, now pesters the party with the incoherent rants of a man driven mad by a botched invisibility spell.",
    51: "A drunken dwarf staggers along, challenging everyone to a wrestling match.",
    52: "A goblin, on fire, runs shrieking past the party.",
    53: "A rock with an odd, glowing rune sits by the road ahead.",
    54: "A noble, disguised as a filthy beggar, tests the party's compassion and generosity. If they pass whatever standard he sets, then he becomes a source of various quests that require personal sacrifice to accomplish.",
    55: "A circus is set up alongside the road. A barker on the roadside cajoles you to 'come inside and see what wonders it holds.'",
    56: "The road crests a hill, and spread out before the group is a stunning, sweeping vista of the land beyond. A painter sits nearby, capturing the scene, and asks the group to pose for his foreground.",
    57: "An overturned rowboat sits on the side of the road. There is no river or stream nearby. Under the rowboat is an entrance to a lair.",
    58: "A wandering cleric begs the heroes to recover a relic for them.",
    59: "A road sign saying where you came from is ahead of you.",
    60: "A group of guardsmen hang wanted posters on trees. One face looks familiar to a PC.",
    61: "A carriage is stuck high up in a tree.",
    62: "In the morning while breaking camp, the PCs spot a bush that wasn't there before.",
    63: "A beautiful woman, adorned in the robes of an enchantress, emerges from hiding near the road and implores you to lend her aid.",
    64: "The road is lined with snakes sleeping in the sun.",
    65: "A necromancer uses his talents to animate animal and human corpses and forces them to perform in a roadside circus. The townsfolk from a nearby village seem to enjoy the show a bit too much.",
    66: "A chain gang digs ditches beside the road.", 
    67: "A traveling minstrel challenges the wisest looking member of the party to a storytelling contest.",
    68: "A wizened tinker sells charms from his cart: dried frogs, finger bones, cat skulls, and the like. Leaving him, you turn to find he is eerily out of sight altogether.",
    69: "A paladin of a holy church and his retinue have ridden out on a holy crusade against evil and demand others who serve the cause of good to join their cause on the spot.",
    70: "A majestic elk sprints past with something golden caught in its antlers.",
    71: "A stranger on the road tells each PC to repent of their sins. He knows details.",
    72: "A door stands beside the road, but there is no sign of the rest of the house.",
    73: "A wine merchant's wagon has shattered a wheel and he offers passers-by cut rate prices on his wares as it is getting repaired.",
    74: "An ugly old woman struggles to bring her wash basket of wet clothes up from the creek to the road. She stumbles and drops the laundry back down the slope.",
    75: "A monk, collapsed and bleeding on the roadside, pushes an unremarkable ring into a PC's hands and desperately whispers, “You must…” before exhaling his last breath.",
    76: "A lost gnome asks for directions.",
    77: "A dead raven lies on the road, pierced by a bright blue fletched arrow.",
    78: "A table on the roadside holds a large basket of fresh vegetables. A sign reads “1 copper a bunch: honesty is a virtue!”",
    79: "The road is littered with bear traps.",
    80: "The group arrives late at night at a tiny village straddling the road. They secure accommodation and food from the friendly locals and fall asleep. In the morning the village is empty and ruined, as if abandoned years ago.",
    81: "As the road passes through a hilly region, you spy a cave, from which can be heard the voice of a singing female.",
    82: "As you turn the corner, a dwarf and elf are standing over a stack of goblin corpses. They argue over the kill count.",
    83: "The party notices a sudden and drastic change in temperature, then just like that, things are back to normal.",
    84: "A little girl is watching you from just off the road. The next time you glance over, you see a wolf run away.",
    85: "Scratched into the dust of the road are the words, “Good luck tomorrow. You're going to need it.”",
    86: "The entire party suddenly loses their bearings and realize that they've walked the same mile three times. Are they road weary or are they caught in something manipulating them.",
    # From litrpgreads site 1:
    87: "Two gnomes approach the party and ask if they have seen a halfling nearby. If the party says no, the gnomes will be completely flabbergasted, and ask how they could have missed him if he was anywhere nearby, as he is very easy to see. If the party says yes, the gnomes will scamper off in whichever direction the party points. If the players ask more, the gnomes' names are Durg and Dung, and they are part of a group of gnomes who are traveling to a distant lands to search for similarly minded individuals.",
    88: "A hooded figure stands in the center of the road. The hood is wrapped tightly around their face, but they appear to be a human woman. She will ask the party if they are travelers heading in any particular direction, and if they say they are just traveling, she will ask them if they could travel with her to a nearby village, as she has recently escaped from a prison camp where she had been held prisoner. Her captors have returned looking for her, and she has little time to get away. If the party says no, she will thank them for their time and leave. If the players say yes, she will join them but remain uncharacteristically quiet unless questioned.",
    89: "An old man is walking down the road, dressed in strange garb, and muttering to himself in a foreign language. If he sees the party, he may stop and ask if they know where “it” is. If the players ask about “it” the man will reply “the one that is coming”. He will then continue to mutter and walk off. After a moment, the party may hear the man say in a louder voice “oh, good! You know where it is. Thank you!” The man is quite insane and might be persuaded to give up all his possessions for information on “it.”",
    90: "A lone horse is wandering down the road, kicking at the dirt with one of its hooves. When the horse sees the party, it will start trotting, and then galloping towards them until it is quite close, at which point it will suddenly stop and run away.",
    91: "A young woman is standing in the middle of the road, waiting for someone. She is dressed in fine clothes, but she looks worried. When she sees a party approaching, she moves to one side of the road and bows low in a sign of respect. If any member of the party stops to talk to her, she will try to explain that she is a messenger from her village, and she has been sent to find a great hero, or perhaps a group of heroes so that they may come back to her village and rid it of a group of men who are terrorizing the town. One of her uncles has been killed, her brother is missing, and all the people of the town are hiding in their houses, afraid because they do not know how many more will fall.",
    92: "A small camp has been set up on the side of the road. There is a fire, with a pot hanging over it. There are no people there, but there is a note, held down by a rock. If the party investigates, they will find it is a note that says “hello traveler's, come sit by our fire and share a meal.” There are cups, bowls, and spoons on the ground. Nobody will ever return to the camp.",
    93: "A loud noise like a cat screeching or a baby crying is heard from inside the forest where the party is facing. The noise will go on for a few minutes and then stop abruptly.",
    94: "A man runs into the party from the opposite direction, holding a bloody dagger and shouting that someone was trying to kill him. If he sees there are no attackers around, he will drop the dagger and run away.",
    95: "A group of men are running down the road, and they are dressed in armor that doesn't fit any known culture. They shout questions at the party, like where are they? And what is going on? They are panicked and scared, and they will run away if questioned too much. If attacked, the men will flee and will not fight back.",
    96: "A man is sitting on the side of the road, eating a very strange looking fruit. He sees the party and laughs, asking if they would like to try his fruit. When the players ask what it is, the man says it is known in his land as the 'fruit of the gods', and he is willing to share a bite with any one of them, as long as they do not tell anyone what it tastes like. The fruit is sweet but will result in a stomach ache one hour later, causing penalties if in a combat situation.",
    97: "Three dogs scurry across the road in front of the party, barking at each other and running around. If the party tries to chase them, they will have disappeared without a trace.",
    98: "A group of women are walking on the side of the road wearing heavy robes, and they are singing a solemn song. They are also carrying baskets of fresh fruits. When the party comes close, one of the women will hold out an odd looking fruit and ask if any of the party would like to try it. When asked what it is, she will say it is a type of fruit the women in her village have been growing for years, but they only share it with the heroes. It is slightly sweet and very filling.",
    99: "The party sees a dead body on the road. It is a human male, dressed in tattered clothing, and there is a knife sticking out of his chest. The body has not started to decompose, and it is likely that whoever killed him was still around when he was killed. The body is carrying an old backpack with a few copper coins in a belt pouch.",
    100: "The party sees a human man running from the forest, holding his arm and crying out for help. He is unarmed and wearing ragged clothing. He will run to the party and tell them that a group of men tried to kill him, and they were coming after him. If any of the players ask about the men who attacked him, he will say they were carrying swords, and even though he doesn't remember much from the fight, he remembers that one of them had a scar over his right eye. The man will be terrified if attacked or questioned further, and will run away.",
    101: "A group of men are sitting on the side of the road near a fire, roasting small birds over the flames. When the party comes near, the men will ask if they would like to join them. The birds are cooked, and they have already started to eat. If the party accepts, the men will open up and share a legend or two about the local region.",
    102: "The party hears the crackling of flames, and they see a man sitting by a campfire, roasting a small bird over the flames. He looks up and sees the party, and he will greet them and invite them over to his camp. The camp is a simple one, with a small tent and a satchel that he has by his side. He has absolutely nothing else, and there are no possessions around. If bribed with alcohol or coins, he will tell a few tall tales before going to bed.",
    103: "A small group of men are gathered around a crate, cursing and grumbling. They are dressed in simple clothes and have the look of dock workers. One of them turns and shouts to the party, asking if they are going to help, but his tone is less than friendly. The crate is nearly 2 meters square, and one of the men has a crowbar. They need help moving the crate up the road. If the party refuses, the men will yell about not being able to get help anymore before getting back to work. The crate is rather heavy for its size, and it is impossible to open without a crowbar.",
    104: "The party comes upon a large tree that has fallen over, completely blocking the road. It is a massive tree. The trunk is two meters wide, and it has fallen in such a way that it is still attached to the low lying branches. An axe is stuck in the tree trunk, and it has been left by the person who felled it. A local constable will come by and accuse the players of cutting it down. They can pay the 10 silver piece fine or talk their way out of it.",
    105: "A group of men are walking down the road, and they appear to be completely drunk. The leader of the group is shouting and arguing with the rest of his companions, and he is the only one not staggering. When the party comes near, the leader will shout at them, trying to get them to come over. He has gone through his companions money, and he needs more. They can give him whatever they want, and he will be happy. If refused, the man will continue down the road, still shouting, and the party will have to avoid all of the men who are staggering up and down the road.",
    # From litrpgreads site 2:
    106: "You come across a hexagonal hay wagon pulled by three cows with the sound of a bard playing inside. If you approach, you are offered a ride.",
    107: "You see a woman standing by a tree, holding a bundle. She asks you to hold it for a moment, and she runs off. When you open the bundle, you find a newborn baby.",
    108: "You come across a troll passed out on the side of the road.",
    109: "You come across a horse whose rider has fallen off. The horse will let you mount him if you can wake him up.",
    110: "You come across the burnt remains of a wagon.",
    111: "You see a man in armor, waving his sword in the air, demanding that people move out of the way.",
    112: "You see three men in animal masks, juggling fruit.",
    113: "You come across a blacksmith, who claims that he will pay you to watch him while he runs errands.",
    114: "You come across a man who invites you to play a game. If you win, you get a prize. If you lose, you owe him a favor.",
    115: "You come across a group of people arguing about a hill giant.",
    116: "You see a group of large men standing around a pit.",
    117: "You see four men dressed in black, riding horses.",
    118: "You see a wagon being pulled by a giant snail. A wizard tips his hat as he passes.",
    119: "You come across a group of young men parading down the road dressed in costumes.",
    120: "You see a man and a woman standing next to a wagon, arguing. If you tell them to make up, they will ask you to choose their punishment.",
    121: "Two men are arguing about a goat.",
    122: "Two men are arguing about the value of a bridge. If you offer to buy it, one of them will sell it to you for 10 silver pieces.He does not own the bridge. He's just hungry.",
    123: "You see a loaded cart that is trapped. If you touch it, it will explode. A group of bandits will then attack.",
    124: "A cart is being pulled by a giant ox. The farmer riding in front says, “Hello! Goodbye!”",
    125: "As you approach a barn, someone comes out and invites you in for some cider. If you drink it, you will be poisoned.",
    126: "You come across a wineskin on the side of the road. It never runs out of wine.",
    127: "You see a man carrying a large wooden box. He will offer to give it to you, but he wants you to answer three riddles. If you fail to answer, he will become enraged and attack.",
    128: "You see a farmer who claims to have been cursed. As you watch him, he transforms into a unicorn and trots away.",
    129: "You see a man carrying a board that has a long message written on it. It is a letter from a father to his son. If you stop to read it, he will steal something of yours that you will never get back.",
    130: "You see a sign that says, “Fork in the road. Go left.”",
    131: "A man dressed in black is standing in the distance. If you approach, he will ask you if he can buy your soul for 10,000 gold pieces.",
    132: "You see a stack of coffins. They are all empty.",
    133: "You see a barn painted on the side of the road. A board is nailed to the wall that says, “Welcome to Barnsville. Population 37 rats!”",
    134: "You see three old men carrying a heavy load down the road. If you help them, they will invite you over for dinner. They are three brothers.",
    135: "A bunch of men are standing in the road, arguing about a wooden barrel.",
    136: "You see a man carrying a bucket with a sign that says, “I am lost. Will you show me the way to the nearest tavern?” If you agree, he will follow you around for the rest of the day, slowing you down.",
    137: "You see a man in the distance, waving his arms.",
    138: "You come across a man digging a hole. When you ask him what he is doing, he says that he is burying a vampire queen who was killed by a paladin. He's actually burying his mother in law.",
    139: "A man is standing in the road with a sign that says, “I'm lost.” If you try to give him directions, he will demand donations.",
    140: "You see men dragging a large wooden barrel. They are too drunk to explain what is in the barrel, but it is heavy and is not beer.",
    141: "You see a group of men tossing a ball around. If you join in, it will quickly become very competitive.",
    142: "You see a group of men carrying a dead man behind them.",
    143: "You see a group of farmers arguing about what crop to plant.",
    144: "You see a man in the distance. He's very angry at someone named 'Rupert' He will engage players in conversation, angry about Rupert, until he is calmed/lied to, or he is given directions to find Rupert.",
    145: "You see a group of men digging a hole. When you ask them what they are doing, they say that they are burying their friend, who has been gravely injured.",
    146: "You see a man in the distance. He is walking with a limp. If you approach him, he will tell you that he has been attacked by a group of men, who stole his money and kicked him in the shin really hard. Really hard!",
    147: "You see a group of young men examining an old helmet, with various things growing out of it, including plants, fungi, and insects.",
    148: "You see a group of crying young boys and girls. “Our parents were taken away by an ogress! It was horrible!”",
    149: "You see a group of children near a dead campfire. They will ask the players to listen to their tale of woe. The children are offspring of the bandits hiding nearby.",
    150: "You see a group of young men who are apparently fishermen. They do not have any fish, but they do have a fish shaped hat and fish shaped shoes. They claim to be from the future.",
    151: "You see a group of men fighting over a piece of food. They will attack the party if not fed.",
    152: "You see a group of merchants in colorful clothing, with all sorts of trinkets and baubles for sale. They are supposedly the only source of the items that they are selling.",
    153: "You see a group of rangers in full camouflage. They're embarrassed when you notice them.",
    154: "A group of men in matching clothing are having an arm-wrestling competition on the side of the road. Betting is encouraged.",
    155: "An old beggar is lying on the side of the road.",
    156: "You see a group of men running away from something. It is unclear what they are running from. They do not stop.",
    157: "You see a group of men and women inspecting a dead body. They are very upset and will not allow the party to investigate the body.",
    158: "As you continue down the road, you hear a loud noise from ahead. It sounds like a wagon full of gears and scrap metal is careening down the road. A traveling gnome trinket offers to sell you his wares.",
    159: "You hear a loud squawking from above. A large vulture is circling the party.",
    160: "A man in a wagon is asking for protection to rest for the night. He has a large amount of gold in a chest.",
    161: "A group of men is in a wagon. They are insane and will not let you pass.",
    162: "There is a group of men at the side of the road arguing over some gold.",
    163: "A group of men are on horseback arguing with a merchant.",
    164: "There is a small pond with a few ducks swimming in it.",
    165: "A group of young children are playing a game of “Hide and Seek” in a nearby field.",
    166: "A group of children are running through the forest, laughing and playing tag.",
    167: "A group of children are playing a game of tag in a nearby meadow.",
    168: "A group of adults are having a discussion in a small clearing. You can't quite make out what they are discussing.",
    169: "A maiden is sitting on a rock at the side of the road looking sad.",
    170: "A small cottage is in the distance, smoke is billowing from the chimney.",
    171: "A small house is on the side of the road with a sign that reads “Cobblestone Inn”.",
    172: "A horse-drawn wagon is stalled in the road. A man is arguing with a farmer.",
    173: "A small dragon is sitting on the side of the road playing with a pile of rocks.",
    174: "A small black kitten is sitting by the side of the road. It hisses right before a witch appears and attacks.",
    # Johnn Four
    175: "A passing mail-courier's horse gets spooked and throws courier. The courier dies in the fall, and the mail bag has the seal of the King's Head of Intelligence.",
    176: "A travelling blade-sharpener offers a special deal to the PCs to improve their magic weapons, but later the PCs discover the magic in the blades seems to be gone.",
    177: "A desperate man offers to sell the group a 'magic' acorn for a pittance. If the PCs buy it, the man runs away laughing madly, shouting 'I'm free! Free at last! You poor fools!'",
    178: "After sleeping on the roadside, the party wakes to find their entire camp surrounded by dew-spangled spider webs, yet they are unharmed.",
    179: "The group passes an old farmer and his nag heading toward the same town the PCs are heading toward. He gives them a wave and a gap-toothed smile. A little while later they pass him again. And then again....",
    180: "An earthquake drops the group and a large section of road into a sinkhole or chasm.",
    181: "The group comes to a wilderness trading post on the trail. The cantankerous oldtimer who runs it offers a bounty for scalps",
    182: "An otherwise empty stretch of highway, with two rival taverns facing each other across the road. The publicans try to outdo each other loudly on the discounts and benefits of their respective establishments to the party. Both seem desperate for customers.",
    183: "A wayfarer's tavern with the windows and doors boarded up from the inside and horrible claw-marks on the outside",
    184: "A knight bearing the crest of a local lord is found rusted into his armour, in an uncomfortable position, by the side of the road.",
    185: "A belligerent drunk wanders into the group's path demanding alcohol, money and to marry their horse.",
    186: "A meteorite crashes to earth in the middle of the road.",
    187: "The party find a child at the base of a tree trying to rescue a cat caught high in the branches. While the party's attention is diverted upward the little pickpocket goes to work.",
    188: "A pleasant and polite gentleman in a smart carriage stops the party for directions and news of the road. But in the trunk lashed to the back the party hear children crying.",
    189: "A group of bandits arguing and blaming each other over the chest of something useless they just stole (feather dusters, mouse-traps, fishing weights).",
    190: "A prison work-gang and their guards are rebuilding part of the road. The convicts use the arrival of the party as an opportunity for escape.",
    191: "The party find a trail of gold coins leading off the path.",
    192: "On a wooded trail, just around a turn in the road, a rope has been strung between two trees high enough to catch a mounted rider. A horse, still saddled, grazes nearby and there's blood smeared on a nearby tree.",
    193: "The party starts finding neatly severed body parts discarded on the road. An ear, then a finger, then a tongue.",
    194: "A large, iron-banded chest lies half buried in mud, as if it fell off the back of a wagon.",
    195: "A toll-booth with guard and an official Inspector who wants to confiscate something strange or valuable.",
    196: "A roc/dragon/flying carpet speeds overhead and drops something glinting into the wilderness near the road.",
    197: "An old woodsman, with a broken axe nearby and a hastily bandaged and bleeding leg, slumps against a tree trunk.",
    198: "A travelling salesman and his gaudy cart, complete with fast-talking snake-oil offers and a dancing monkey.",
    199: "A new sign pointing down a narrow path off the road saying, 'Fresh Berries - Pick your Own.'",
    200: "A lost child cries on the side of the road.",
    201: "A pack of starving wolves fights over the body of a lone traveller",
    202: "A band of lepers or plague-carriers on their way to a nearby spring with supposed healing properties.",
    203: "A widow/widower and children planting a tree/flowers for their loved one, who died on the road.",
    204: "A group of drunk young noblemen pass the PCs, racing their expensive horses.",
    205: "A burnt-out toll-station, with the murdered bodies of the toll inspectors still scattered around.",
    206: "The group meet an uncannily similar party of adventurers going the opposite way.",
    207: "The group is followed from the last town by a band of children who want to go on adventures with them.",
    208: "A paved road recently rebuilt with stone from nearby ruins. The group notices some stones are carved with odd patterns. Put together, the patterns make up a mural showing the location of a valuable treasure/dungeon/great monster",
    209: "A pompous noble stands in the road, flogging and shouting at his injured horse",
    210: "The party see a mass of crows circling above a known safe haven/tavern/camping spot that lies just ahead, and the smell of smoke and roast meat hangs in the air.",
    211: "A tall rock overlooks the road. As the group passes, a filthy hermit babble prophecies and throws rotten food at them.",
    212: "An elderly woman wanders the verge of the road, bent double and carrying a basket of foraged produce. She asks the party for a ride on their wagon to ease her tired feet.",
    213: "A rider stops to ask for hurried directions. The rider thanks them and races ahead. When the PCs reach the next town, fresh Wanted posters are being nailed up with the group's faces sketched on and accusations of heinous crimes in the last town back. The locals all stare at the PCs.",
    214: "A voice from the bushes by the road shouts, 'We have you surrounded, Torvik! Your villainy ends here!' But who's Torvik?",
    215: "A young woman with a crying baby wrapped in a shawl is hotly pursued by a band of rough-looking men.",
    216: "A beehive buzzes angrily on a branch overhanging the road, and beneath it a figure lies gasping and puffy with dozens of stings.",
    217: "The road is rigged with an obvious and clumsily/hastily made trap. The PCs can hear drunken giggling from the undergrowth",
    218: "A group of people stand around a burned corpse nervously looking at each other, then in the PCs' direction. Some try to quickly leave the scene while the more brave and curious continue to wait for the PCs' approach.",
    219: "A nearby summoning ritual has gone awry and a demon rampages across the road.",
    220: "Two precocious children offer to buff shields or dust boots for money. They follow PCs at a distance calling them names if rebuffed.",
    221: "A wandering soothsayer demands a contest of will before revealing a prophecy.",
    222: "Two ranks of royal guard form between you and an oncoming procession, allowing the large entourage and perhaps the king himself - difficult to say with all the covered carriages - to pass by.",
    223: "Eying you warily, another party of adventurers allows you wide berth as they try to make their way around you.",
    224: "Near the road is a mound the size of a grave, obviously of recent excavation, marked at its head by an upright stake.",
    225: "The broken hull of a lost ship beckons absurdly from the forest edge.",
    226: "A damaged slaver wagon sinks swiftly into the marsh. Tethered hostages struggle frantically to escape.",
    227: "As you get the roadside campfire going and put on the pot of beans, the party is surprised by the manifestation of a number of ghostly travellers, silently staring into the fire and attempting to warm their extended, translucent hands",
    228: "The road leads through a tunnel. Halfway through, the party finds a major wall and roof collapse revealing a large passage running adjacent to the road, with flickering lights visible further in",
    229: "A crazy backwoods seditionist has made up his own country, with its own legal system and economy only he uses. He's a fairly powerful hedge wizard, and demands the PCs obey his laws.",
    230: "A leathery-faced farmer asks for help. He runs a successful bee farm and produces the best honey in the land...or he did. Yesterday he purchased a new queen bee, but after gorging herself on the farmer's existing honey overnight, the queen has grown into a giant bee and gathered the farmers' bees into an aggressive swarm that attacks anyone in the vicinity.",
    231: "A couple has chosen a small glade along the road for their wedding. However, the bride is weeping and the wedding party is frantically scouring the grassy area, for it seems the ring has been lost or maybe stolen.",
    232: "A disreputable merchant has set up a road stall that sells pies. Unfortunately, the pies are made with rotten meat, and whilst the pies taste fine, all who eat them become violently ill.",
    233: "A young couple feverishly digs alongside the road, bickering all the while. It seems they're after something valuable buried by the road.",
    234: "The PCs encounter the corpse of a rare monster",
    235: "A traveler with the PCs slowly becomes undead.",
    236: "A vampire hunter seeks to temporarily join the team, warning of the dangers of his prey. Is the hunter actually the vampire?",
    237: "A militia practices their ranging with a local catapult. For fun, a few decide to launch themselves into the lake beside the road. Looks like fun, maybe they are willing to share their new toy",
    238: "A trail of blood leads from the road to a nearby barn.",
    239: "An ogre strides from the wilderness, offering his services as guide and bodyguard on a dangerous stretch of road. If paid, he serves admirably and departs. If attacked, he signals others of his band hidden nearby and they swarm to attack.",
    240: "A travelling peddler sells curses.",
    241: "A path from the road leads to a collapsed house overgrown with foliage.",
    242: "A collie stands in the middle of the road, it awaits the PCs and then tries to lead them somewhere. The dog leads them to an abandoned well in the woods. Ideas for the well: It leads to a dungeon with the collie's lost master trapped inside. Or 'Timmy' is a troll using the dog to lead prey to his well.",
    243: "On the side of the road an old man and woman yell at each other about who forgot to pack lunch.",
    244: "Many years of spilled blood at a contested crossroads has lent the road itself a dark sentience. Those who camp nearby suffer nightmares and the attacks of evil ghosts.",
    245: "Ahead, on the side of the road, sits a man, apparently a farmer. In his hands is a shredded blue dress, the size of a child and he clutches it to his chest, sobbing. Behind him is the smoldering ruins of a farmhouse.",
    246: "A dead horse, in full tack, lies dead in a ditch. The saddle bags are full of adventuring equipment, a few gems, a gilded goblet, and a map to what appears to be a treasure trove. Cursory examination shows signs of a struggle and drag marks leading further off the road.",
    247: "A wagon ahead has overturned. It appears to have been carrying four large metal containers that are now scattered about. The driver lies dead, some wicked pustules marking his exposed skin. One of the containers looks like it might be leaking some sort of liquid.",
    248: "A wizard lies slain in the road, his insane Homunculus protects his body and belongings, swearing vengeance on all who disturb the corpse."
}