# Dicts for Roadside Encounters
# Each type of encounter will have its own dictionary, with combat encounters having CR able to be output

# Sources:
# https://nerdsonearth.com/2016/02/100-dungeons-and-dragons-roadside-encounters-2/

event = {
    1: "A huge nest has fallen from a tree on the side of the road. The strange-looking eggs within seem on the verge of hatching.",
    2: "A dwarf falls from the sky onto the road with a splat. (Did a creature drop it, was he launched into the air, did he fall from a floating fortress?)",
    3: "A row of severed heads on spikes and a warning sign claiming, 'Dis Rode Belong Negan'",
    4: "A very small goblin wearing an old carpet as a cape leaps into the path and demands tribute.",
    5: "A crazed halfling, starved out of his mind, jumps to the backs of the PCs and rips their packs apart with his teeth in search of food.",
    6: "A bounty hunter tracks his target.",
    7: "A lush garden is filled with ripe vegetables. It is protected by a magical ward, but what is triggered when entering the garden?",
    8: "A monstrous mount is ridden by a gnome. Friend or foe?",
    9: "Two guards hold a wanted poster. They carefully studies the party as they pass by.",
    10: "A smiling roadside merchant roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
    11: "A chatty bard walks alongside the party. Time for an exposition dump!",
    12: "A bridle ties a well-groomed speckled horse to a nearby tree. The horse is fitted with an elegant but empty saddle. Who does it belong to? Do the PCs take it?",
    13: "A powerful storm forced you to take the only available refuge: an elderly couple's home just off the side of the road. The two room home holds numerous open cups of the same pungent liquid.",
    14: "A naked bard asks for a lift to the nearest inn where he left his clothes and money.",
    15: "Alongside the road, a charlatan asks the party if they want to see a performance of his trained pets. The slightest affirmative answer causes Steve to give a whistle, and a huge swarm of ravenous locusts suddenly manifests.",
    16: "A fat friar hurries past the PCs mumbling, 'It isn't fair...'",
    17: "A witch is tied to a stake, the body still smoking",
    18: "Three young men work on tipping over an occupied outhouse.",
    19: "The PCs feel like they are being followed. Who is hunting them?",
    20: "Three types of meat hang on a spit over a campfire. It is clear that it is three types of humanoids that hang over the flames.",
    21: "A well-spoken bugbear wearing fine studded leather armor is trapped under a fallen tree. He begs the party to come to his aid.",
    22: "A ranger stops by the group's camp one night and gives them advice on the trail ahead, including places to camp and a tavern where they can get good rates if they mention his name. All his advice is impeccable, but when they mention his name at the tavern, they're told he died years ago on that very road.",
    23: "A shopping list for potions lies on the ground.",
    24: "You find the remains of a pouch that contains coins fro ma land you do not recognize.",
    25: "The party hears a long stream of curses further up the road. Then they spot a head in the road. A person is still alive, buried up to his neck!",
    26: "An arrow hits a nearby trunk, a message wrapped around the shaft.",
    27: "A loaded wagon travels down the road toward the party, but it has no apparent means of propulsion.",
    28: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    29: "As bandits attack, the PCs realize a friend of theirs is among the robbers.",
    30: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    31: "A tree falls onto the road. Then a fireball blows up the tree. It appears the PCs are in the middle of a skirmish between a witch and wizards.",
    32: "Flowers by the roadside turn their heads to follow the party, and they're getting larger.",
    33: "An overturned beer cart lies in the road. Nearby, an enormous troll snores loudly, surrounded by empty kegs.",
    34: "A set of shackles lies at the side of the road.",
    35: "A village can be seen to the west. It isn't on any of the maps.",
    36: "Three pilgrims trudge along the dusty road, an old man and two young men. Simple travelers? Or are they more than they seem?",
    37: "You stumble upon an old scroll case wedged between a tangle of tree branches. Inside is a village's charter of rights and freedoms.",
    38: "A dead magic user clutches a scroll in his stiff hand. The scroll says something important.",
    39: "A single giant footprint lies along the path. There are no other signs of such footprints in the area.",
    40: "An exotic, almost alien weapon or tool lies on the side of the road.",
    41: "Two other adventuring groups are arguing in the middle of the road.",
    42: "You see a man-sized shadow from the left side of the road waving its arms at you. 'Over here, quickly, I've caught one!'",
    43: "A person fleeing arranged marriage seeks refuge with the PCs.",
    44: "Picked mushrooms lay on stump to dry.",
    45: "A strange old man offers the PCs a scroll in a language they cannot read.",
    46: "Gnomes are holding a yard sale! They have any number of strange and fascinating contraptions.",
    47: "Someone has scattered caltrops across the road.",
    48: "You encounter a monk, a monkey, a turtle and a pig, all heading west.",
    49: "A weathered sign points off the road, yet with no apparent trail to follow.",
    50: "A formerly brilliant wizard, now pesters the party with the incoherent rants of a man driven mad by a botched invisibility spell.",
    51: "A drunken dwarf staggers along, challenging everyone to a wrestling match.",
    52: "A goblin, on fire, runs shrieking past the party.",
    53: "A rock with an odd, glowing rune sits by the road ahead.",
    54: "A noble, disguised as a filthy beggar, tests the party's compassion and generosity. If they pass whatever standard he sets, then he becomes a source of various quests that require personal sacrifice to accomplish.",
    55: "A circus is set up alongside the road. A barker on the roadside cajoles you to 'come inside and see what wonders it holds.'",
    56: "The road crests a hill, and spread out before the group is a stunning, sweeping vista of the land beyond. A painter sits nearby, capturing the scene, and asks the group to pose for his foreground.",
    57: "An overturned rowboat sits on the side of the road. There is no river or stream nearby. Under the rowboat is an entrance to a lair.",
    58: "A wandering cleric begs the heroes to recover a relic for them.",
    59: "A road sign saying where you came from is ahead of you.",
    60: "A group of guardsmen hang wanted posters on trees. One face looks familiar to a PC.",
    61: "A carriage is stuck high up in a tree.",
    62: "In the morning while breaking camp, the PCs spot a bush that wasn't there before.",
    63: "A beautiful woman, adorned in the robes of an enchantress, emerges from hiding near the road and implores you to lend her aid.",
    64: "The road is lined with snakes sleeping in the sun.",
    65: "A necromancer uses his talents to animate animal and human corpses and forces them to perform in a roadside circus. The townsfolk from a nearby village seem to enjoy the show a bit too much.",
    66: "A chain gang digs ditches beside the road.", 
    67: "A traveling minstrel challenges the wisest looking member of the party to a storytelling contest.",
    68: "A wizened tinker sells charms from his cart: dried frogs, finger bones, cat skulls, and the like. Leaving him, you turn to find he is eerily out of sight altogether.",
    69: "A paladin of a holy church and his retinue have ridden out on a holy crusade against evil and demand others who serve the cause of good to join their cause on the spot.",
    70: "A majestic elk sprints past with something golden caught in its antlers.",
    71: "A stranger on the road tells each PC to repent of their sins. He knows details.",
    72: "A door stands beside the road, but there is no sign of the rest of the house.",
    73: "A wine merchant's wagon has shattered a wheel and he offers passers-by cut rate prices on his wares as it is getting repaired.",
    74: "An ugly old woman struggles to bring her wash basket of wet clothes up from the creek to the road. She stumbles and drops the laundry back down the slope.",
    75: "A monk, collapsed and bleeding on the roadside, pushes an unremarkable ring into a PC's hands and desperately whispers, “You must…” before exhaling his last breath.",
    76: "A lost gnome asks for directions.",
    77: "A dead raven lies on the road, pierced by a bright blue fletched arrow.",
    78: "A table on the roadside holds a large basket of fresh vegetables. A sign reads “1 copper a bunch: honesty is a virtue!”",
    79: "The road is littered with bear traps.",
    80: "The group arrives late at night at a tiny village straddling the road. They secure accommodation and food from the friendly locals and fall asleep. In the morning the village is empty and ruined, as if abandoned years ago.",
    81: "As the road passes through a hilly region, you spy a cave, from which can be heard the voice of a singing female.",
    82: "As you turn the corner, a dwarf and elf are standing over a stack of goblin corpses. They argue over the kill count.",
    83: "The party notices a sudden and drastic change in temperature, then just like that, things are back to normal.",
    84: "A little girl is watching you from just off the road. The next time you glance over, you see a wolf run away.",
    85: "Scratched into the dust of the road are the words, “Good luck tomorrow. You're going to need it.”",
    86: "The entire party suddenly loses their bearings and realize that they've walked the same mile three times. Are they road weary or are they caught in something manipulating them."
}