# Dicts for Roadside Encounters
# Each type of encounter will have its own dictionary, with combat encounters having CR able to be output

# Sources:
# https://nerdsonearth.com/2016/02/100-dungeons-and-dragons-roadside-encounters-2/
# https://litrpgreads.com/blog/rpg/random-encounter-table-non-combat-d20
# https://litrpgreads.com/blog/rpg/100-dnd-random-road-encounters

# Dict for handling rp/sidequest based events. Currently there are combat events in here as there is no combat event dict yet.
event = {
    # From nerdsonearth:
    1: "A huge nest has fallen from a tree on the side of the road. The strange-looking eggs within seem on the verge of hatching.",
    2: "A dwarf falls from the sky onto the road with a splat. (Did a creature drop it, was he launched into the air, did he fall from a floating fortress?)",
    3: "A row of severed heads on spikes and a warning sign claiming, 'Dis Rode Belong Negan'",
    4: "A very small goblin wearing an old carpet as a cape leaps into the path and demands tribute.",
    5: "A crazed halfling, starved out of his mind, jumps to the backs of the PCs and rips their packs apart with his teeth in search of food.",
    6: "A bounty hunter tracks his target.",
    7: "A lush garden is filled with ripe vegetables. It is protected by a magical ward, but what is triggered when entering the garden?",
    8: "A monstrous mount is ridden by a gnome. Friend or foe?",
    9: "Two guards hold a wanted poster. They carefully studies the party as they pass by.",
    10: "A smiling roadside merchant roasts rats, frogs, and squirrels on sticks. He offers a bite to the PCs.",
    11: "A chatty bard walks alongside the party. Time for an exposition dump!",
    12: "A bridle ties a well-groomed speckled horse to a nearby tree. The horse is fitted with an elegant but empty saddle. Who does it belong to? Do the PCs take it?",
    13: "A powerful storm forced you to take the only available refuge: an elderly couple's home just off the side of the road. The two room home holds numerous open cups of the same pungent liquid.",
    14: "A naked bard asks for a lift to the nearest inn where he left his clothes and money.",
    15: "Alongside the road, a charlatan asks the party if they want to see a performance of his trained pets. The slightest affirmative answer causes Steve to give a whistle, and a huge swarm of ravenous locusts suddenly manifests.",
    16: "A fat friar hurries past the PCs mumbling, 'It isn't fair...'",
    17: "A witch is tied to a stake, the body still smoking",
    18: "Three young men work on tipping over an occupied outhouse.",
    19: "The PCs feel like they are being followed. Who is hunting them?",
    20: "Three types of meat hang on a spit over a campfire. It is clear that it is three types of humanoids that hang over the flames.",
    21: "A well-spoken bugbear wearing fine studded leather armor is trapped under a fallen tree. He begs the party to come to his aid.",
    22: "A ranger stops by the group's camp one night and gives them advice on the trail ahead, including places to camp and a tavern where they can get good rates if they mention his name. All his advice is impeccable, but when they mention his name at the tavern, they're told he died years ago on that very road.",
    23: "A shopping list for potions lies on the ground.",
    24: "You find the remains of a pouch that contains coins from a land you do not recognize.",
    25: "The party hears a long stream of curses further up the road. Then they spot a head in the road. A person is still alive, buried up to his neck!",
    26: "An arrow hits a nearby trunk, a message wrapped around the shaft.",
    27: "A loaded wagon travels down the road toward the party, but it has no apparent means of propulsion.",
    28: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    29: "As bandits attack, the PCs realize a friend of theirs is among the robbers.",
    30: "There is a mysterious flicker ahead, and one member of your party suddenly stops, paralyzed.",
    31: "A tree falls onto the road. Then a fireball blows up the tree. It appears the PCs are in the middle of a skirmish between a witch and wizards.",
    32: "Flowers by the roadside turn their heads to follow the party, and they're getting larger.",
    33: "An overturned beer cart lies in the road. Nearby, an enormous troll snores loudly, surrounded by empty kegs.",
    34: "A set of shackles lies at the side of the road.",
    35: "A village can be seen to the west. It isn't on any of the maps.",
    36: "Three pilgrims trudge along the dusty road, an old man and two young men. Simple travelers? Or are they more than they seem?",
    37: "You stumble upon an old scroll case wedged between a tangle of tree branches. Inside is a village's charter of rights and freedoms.",
    38: "A dead magic user clutches a scroll in his stiff hand. The scroll says something important.",
    39: "A single giant footprint lies along the path. There are no other signs of such footprints in the area.",
    40: "An exotic, almost alien weapon or tool lies on the side of the road.",
    41: "Two other adventuring groups are arguing in the middle of the road.",
    42: "You see a man-sized shadow from the left side of the road waving its arms at you. 'Over here, quickly, I've caught one!'",
    43: "A person fleeing arranged marriage seeks refuge with the PCs.",
    44: "Picked mushrooms lay on stump to dry.",
    45: "A strange old man offers the PCs a scroll in a language they cannot read.",
    46: "Gnomes are holding a yard sale! They have any number of strange and fascinating contraptions.",
    47: "Someone has scattered caltrops across the road.",
    48: "You encounter a monk, a monkey, a turtle and a pig, all heading west.",
    49: "A weathered sign points off the road, yet with no apparent trail to follow.",
    50: "A formerly brilliant wizard, now pesters the party with the incoherent rants of a man driven mad by a botched invisibility spell.",
    51: "A drunken dwarf staggers along, challenging everyone to a wrestling match.",
    52: "A goblin, on fire, runs shrieking past the party.",
    53: "A rock with an odd, glowing rune sits by the road ahead.",
    54: "A noble, disguised as a filthy beggar, tests the party's compassion and generosity. If they pass whatever standard he sets, then he becomes a source of various quests that require personal sacrifice to accomplish.",
    55: "A circus is set up alongside the road. A barker on the roadside cajoles you to 'come inside and see what wonders it holds.'",
    56: "The road crests a hill, and spread out before the group is a stunning, sweeping vista of the land beyond. A painter sits nearby, capturing the scene, and asks the group to pose for his foreground.",
    57: "An overturned rowboat sits on the side of the road. There is no river or stream nearby. Under the rowboat is an entrance to a lair.",
    58: "A wandering cleric begs the heroes to recover a relic for them.",
    59: "A road sign saying where you came from is ahead of you.",
    60: "A group of guardsmen hang wanted posters on trees. One face looks familiar to a PC.",
    61: "A carriage is stuck high up in a tree.",
    62: "In the morning while breaking camp, the PCs spot a bush that wasn't there before.",
    63: "A beautiful woman, adorned in the robes of an enchantress, emerges from hiding near the road and implores you to lend her aid.",
    64: "The road is lined with snakes sleeping in the sun.",
    65: "A necromancer uses his talents to animate animal and human corpses and forces them to perform in a roadside circus. The townsfolk from a nearby village seem to enjoy the show a bit too much.",
    66: "A chain gang digs ditches beside the road.", 
    67: "A traveling minstrel challenges the wisest looking member of the party to a storytelling contest.",
    68: "A wizened tinker sells charms from his cart: dried frogs, finger bones, cat skulls, and the like. Leaving him, you turn to find he is eerily out of sight altogether.",
    69: "A paladin of a holy church and his retinue have ridden out on a holy crusade against evil and demand others who serve the cause of good to join their cause on the spot.",
    70: "A majestic elk sprints past with something golden caught in its antlers.",
    71: "A stranger on the road tells each PC to repent of their sins. He knows details.",
    72: "A door stands beside the road, but there is no sign of the rest of the house.",
    73: "A wine merchant's wagon has shattered a wheel and he offers passers-by cut rate prices on his wares as it is getting repaired.",
    74: "An ugly old woman struggles to bring her wash basket of wet clothes up from the creek to the road. She stumbles and drops the laundry back down the slope.",
    75: "A monk, collapsed and bleeding on the roadside, pushes an unremarkable ring into a PC's hands and desperately whispers, “You must…” before exhaling his last breath.",
    76: "A lost gnome asks for directions.",
    77: "A dead raven lies on the road, pierced by a bright blue fletched arrow.",
    78: "A table on the roadside holds a large basket of fresh vegetables. A sign reads “1 copper a bunch: honesty is a virtue!”",
    79: "The road is littered with bear traps.",
    80: "The group arrives late at night at a tiny village straddling the road. They secure accommodation and food from the friendly locals and fall asleep. In the morning the village is empty and ruined, as if abandoned years ago.",
    81: "As the road passes through a hilly region, you spy a cave, from which can be heard the voice of a singing female.",
    82: "As you turn the corner, a dwarf and elf are standing over a stack of goblin corpses. They argue over the kill count.",
    83: "The party notices a sudden and drastic change in temperature, then just like that, things are back to normal.",
    84: "A little girl is watching you from just off the road. The next time you glance over, you see a wolf run away.",
    85: "Scratched into the dust of the road are the words, “Good luck tomorrow. You're going to need it.”",
    86: "The entire party suddenly loses their bearings and realize that they've walked the same mile three times. Are they road weary or are they caught in something manipulating them.",
    # From litrpgreads site 1:
    87: "Two gnomes approach the party and ask if they have seen a halfling nearby. If the party says no, the gnomes will be completely flabbergasted, and ask how they could have missed him if he was anywhere nearby, as he is very easy to see. If the party says yes, the gnomes will scamper off in whichever direction the party points. If the players ask more, the gnomes' names are Durg and Dung, and they are part of a group of gnomes who are traveling to a distant lands to search for similarly minded individuals.",
    88: "A hooded figure stands in the center of the road. The hood is wrapped tightly around their face, but they appear to be a human woman. She will ask the party if they are travelers heading in any particular direction, and if they say they are just traveling, she will ask them if they could travel with her to a nearby village, as she has recently escaped from a prison camp where she had been held prisoner. Her captors have returned looking for her, and she has little time to get away. If the party says no, she will thank them for their time and leave. If the players say yes, she will join them but remain uncharacteristically quiet unless questioned.",
    89: "An old man is walking down the road, dressed in strange garb, and muttering to himself in a foreign language. If he sees the party, he may stop and ask if they know where “it” is. If the players ask about “it” the man will reply “the one that is coming”. He will then continue to mutter and walk off. After a moment, the party may hear the man say in a louder voice “oh, good! You know where it is. Thank you!” The man is quite insane and might be persuaded to give up all his possessions for information on “it.”",
    90: "A lone horse is wandering down the road, kicking at the dirt with one of its hooves. When the horse sees the party, it will start trotting, and then galloping towards them until it is quite close, at which point it will suddenly stop and run away.",
    91: "A young woman is standing in the middle of the road, waiting for someone. She is dressed in fine clothes, but she looks worried. When she sees a party approaching, she moves to one side of the road and bows low in a sign of respect. If any member of the party stops to talk to her, she will try to explain that she is a messenger from her village, and she has been sent to find a great hero, or perhaps a group of heroes so that they may come back to her village and rid it of a group of men who are terrorizing the town. One of her uncles has been killed, her brother is missing, and all the people of the town are hiding in their houses, afraid because they do not know how many more will fall.",
    92: "A small camp has been set up on the side of the road. There is a fire, with a pot hanging over it. There are no people there, but there is a note, held down by a rock. If the party investigates, they will find it is a note that says “hello traveler's, come sit by our fire and share a meal.” There are cups, bowls, and spoons on the ground. Nobody will ever return to the camp.",
    93: "A loud noise like a cat screeching or a baby crying is heard from inside the forest where the party is facing. The noise will go on for a few minutes and then stop abruptly.",
    94: "A man runs into the party from the opposite direction, holding a bloody dagger and shouting that someone was trying to kill him. If he sees there are no attackers around, he will drop the dagger and run away.",
    95: "A group of men are running down the road, and they are dressed in armor that doesn't fit any known culture. They shout questions at the party, like where are they? And what is going on? They are panicked and scared, and they will run away if questioned too much. If attacked, the men will flee and will not fight back.",
    96: "A man is sitting on the side of the road, eating a very strange looking fruit. He sees the party and laughs, asking if they would like to try his fruit. When the players ask what it is, the man says it is known in his land as the 'fruit of the gods', and he is willing to share a bite with any one of them, as long as they do not tell anyone what it tastes like. The fruit is sweet but will result in a stomach ache one hour later, causing penalties if in a combat situation.",
    97: "Three dogs scurry across the road in front of the party, barking at each other and running around. If the party tries to chase them, they will have disappeared without a trace.",
    98: "A group of women are walking on the side of the road wearing heavy robes, and they are singing a solemn song. They are also carrying baskets of fresh fruits. When the party comes close, one of the women will hold out an odd looking fruit and ask if any of the party would like to try it. When asked what it is, she will say it is a type of fruit the women in her village have been growing for years, but they only share it with the heroes. It is slightly sweet and very filling.",
    99: "The party sees a dead body on the road. It is a human male, dressed in tattered clothing, and there is a knife sticking out of his chest. The body has not started to decompose, and it is likely that whoever killed him was still around when he was killed. The body is carrying an old backpack with a few copper coins in a belt pouch.",
    100: "The party sees a human man running from the forest, holding his arm and crying out for help. He is unarmed and wearing ragged clothing. He will run to the party and tell them that a group of men tried to kill him, and they were coming after him. If any of the players ask about the men who attacked him, he will say they were carrying swords, and even though he doesn't remember much from the fight, he remembers that one of them had a scar over his right eye. The man will be terrified if attacked or questioned further, and will run away.",
    101: "A group of men are sitting on the side of the road near a fire, roasting small birds over the flames. When the party comes near, the men will ask if they would like to join them. The birds are cooked, and they have already started to eat. If the party accepts, the men will open up and share a legend or two about the local region.",
    102: "The party hears the crackling of flames, and they see a man sitting by a campfire, roasting a small bird over the flames. He looks up and sees the party, and he will greet them and invite them over to his camp. The camp is a simple one, with a small tent and a satchel that he has by his side. He has absolutely nothing else, and there are no possessions around. If bribed with alcohol or coins, he will tell a few tall tales before going to bed.",
    103: "A small group of men are gathered around a crate, cursing and grumbling. They are dressed in simple clothes and have the look of dock workers. One of them turns and shouts to the party, asking if they are going to help, but his tone is less than friendly. The crate is nearly 2 meters square, and one of the men has a crowbar. They need help moving the crate up the road. If the party refuses, the men will yell about not being able to get help anymore before getting back to work. The crate is rather heavy for its size, and it is impossible to open without a crowbar.",
    104: "The party comes upon a large tree that has fallen over, completely blocking the road. It is a massive tree. The trunk is two meters wide, and it has fallen in such a way that it is still attached to the low lying branches. An axe is stuck in the tree trunk, and it has been left by the person who felled it. A local constable will come by and accuse the players of cutting it down. They can pay the 10 silver piece fine or talk their way out of it.",
    105: "A group of men are walking down the road, and they appear to be completely drunk. The leader of the group is shouting and arguing with the rest of his companions, and he is the only one not staggering. When the party comes near, the leader will shout at them, trying to get them to come over. He has gone through his companions money, and he needs more. They can give him whatever they want, and he will be happy. If refused, the man will continue down the road, still shouting, and the party will have to avoid all of the men who are staggering up and down the road."
    # From litrpgreads site 2:
}